name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.1
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        #conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
  
  wily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2-beta
        with:
          ref: refs/heads/master
          clean: false

      - name: Set up Python 3.7.1
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wily
      - name: Build wily
        run: |
          wily build generator/ test/ .
          wily diff generator/ -r master
      - name: Show wily report
        run: |
          wily report generator/generator.py
          wily report test/test_generator.py
      - name: Show wily rank
        run: |
          wily rank generator/ 
          wily rank test/ 
          wily rank .

